test_that("Random sampler works", {
  m=load_model_from_xml(paste0(system.file('extdata', package = 'ecocx'),"/anchovy_bay_ecosim_ex.eiixml"))
  factor_list=new_ecosim_factor_set(m)
  factor_list=add_option_ecosim_effort(factor_list,"Baitboats","phase_out",rep(0,get_ecosim_effort_length(factor_list,"Baitboats")))
  df_sample=sampler_random(factor_list, 8)
  expect_length(unique(df_sample$Trawlers),1)
  expect_true(length(unique(df_sample$Baitboats))<=2)
  expect_equal(nrow(df_sample),8)
  expect_equal(ncol(df_sample),4+nrow(summary(factor_list)))
  expect_all_true(summary(factor_list)$name %in% colnames(df_sample))
})
